on: [push, pull_request]

name: "afgs-package-tools"

jobs:
  afgs-package-tools-test:
    name: Test Tools on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: "Build & Test"
      run: |
        python3 -m venv .venv
        .venv/bin/pip3 install setuptools 
        .venv/bin/pip3 install git+https://github.com/AnotherFoxGuy/conan-package-tools@conan2
        .venv/bin/pip3 install -e .[test]
        .venv/bin/python3 setup.py sdist
        cd tests
        ../.venv/bin/pytest -vvv -s
